language: csharp
mono: none
solution: WebApplication1.sln
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
install:
  - nuget restore WebApplication1.sln
script:
  - dotnet test ".WebAndLoadTestProject1/WebAndLoadTestProject1"