language: csharp
solution: WebApplication1.sln
install:
  - nuget restore WebApplication1.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release /p:Platform="Any CPU" WebApplication1.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./WebAndLoadTestProject1/bin/Release/WebAndLoadTestProject1.dll